name: "LlamaIndex"
description: "Framework for building knowledge assistants using LLMs connected to your enterprise data."
url: "https://www.llamaindex.ai"
docs: "https://docs.llamaindex.ai/en/stable/api_reference/llms/openrouter/"
tags:
  - coding
  - research
open_source: "https://github.com/run-llama/llama_index"
date_added: "2026-02-04"